"""refactor model

Revision ID: 010927dfb019
Revises: f86e9f0db915
Create Date: 2022-07-05 16:02:40.822249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010927dfb019'
down_revision = 'f86e9f0db915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('semesters_term_id_fkey', 'semesters', type_='foreignkey')
    op.drop_column('semesters', 'term_id')
    op.drop_constraint('trimesters_term_id_fkey', 'trimesters', type_='foreignkey')
    op.drop_column('trimesters', 'term_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trimesters', sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('trimesters_term_id_fkey', 'trimesters', 'terms', ['term_id'], ['id'], ondelete='CASCADE')
    op.add_column('semesters', sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('semesters_term_id_fkey', 'semesters', 'terms', ['term_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
