"""add rel. to models

Revision ID: 010fb44edf5a
Revises: 9c08324388e6
Create Date: 2022-05-31 11:08:49.652480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010fb44edf5a'
down_revision = '9c08324388e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edu_phases', sa.Column('edu_stage_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'edu_phases', 'edu_stages', ['edu_stage_id'], ['id'], ondelete='CASCADE')
    op.add_column('edu_stages', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'edu_stages', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.add_column('grades', sa.Column('edu_phase_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'edu_phases', ['edu_phase_id'], ['id'], ondelete='CASCADE')
    op.add_column('managers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'managers', ['user_id'])
    op.create_foreign_key(None, 'managers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('schools', sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schools', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'schools', ['manager_id'])
    op.create_foreign_key(None, 'schools', 'managers', ['manager_id'], ['user_id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'school_id')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'manager_id')
    op.drop_column('schools', 'registered_at')
    op.drop_constraint(None, 'managers', type_='foreignkey')
    op.drop_constraint(None, 'managers', type_='unique')
    op.drop_column('managers', 'user_id')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'edu_phase_id')
    op.drop_constraint(None, 'edu_stages', type_='foreignkey')
    op.drop_column('edu_stages', 'school_id')
    op.drop_constraint(None, 'edu_phases', type_='foreignkey')
    op.drop_column('edu_phases', 'edu_stage_id')
    # ### end Alembic commands ###
