"""id error fix

Revision ID: 046a5dcc7dcd
Revises: 28aacd3ac63d
Create Date: 2022-06-15 11:59:49.457057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046a5dcc7dcd'
down_revision = '28aacd3ac63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'staff', ['matric_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    # ### end Alembic commands ###
