"""adding manager table and rel.

Revision ID: 0eb9bb6fe094
Revises: a851fcc214bc
Create Date: 2022-05-30 18:15:52.752901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb9bb6fe094'
down_revision = 'a851fcc214bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schools_admin_id_fkey', 'schools', type_='foreignkey')
    op.drop_column('schools', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('admin_id', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True))
    op.create_foreign_key('schools_admin_id_fkey', 'schools', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
