"""manager-user-school  rel. fix

Revision ID: 168ba730033f
Revises: 334984f98a6e
Create Date: 2022-05-30 18:27:00.900974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168ba730033f'
down_revision = '334984f98a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('manager_id', sa.Integer(), server_default='2', nullable=False))
    op.create_foreign_key(None, 'schools', 'managers', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'manager_id')
    # ### end Alembic commands ###
