"""user-manager-school  rel. update

Revision ID: 1c830e228c8b
Revises: c850733fed06
Create Date: 2022-05-31 10:36:21.190030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c830e228c8b'
down_revision = 'c850733fed06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'managers', ['user_id'])
    op.create_unique_constraint(None, 'schools', ['manager_id'])
    op.drop_constraint('schools_manager_id_fkey', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'managers', ['manager_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_manager_id_fkey', 'schools', 'managers', ['manager_id'], ['id'])
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_constraint(None, 'managers', type_='unique')
    # ### end Alembic commands ###
