"""fix assoc_table

Revision ID: 1ede68e7775d
Revises: a97ebc86801a
Create Date: 2022-06-15 09:08:14.466416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ede68e7775d'
down_revision = 'a97ebc86801a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('managers_user_id_key', 'managers', type_='unique')
    op.add_column('parent_student_assoc', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.add_column('parent_student_assoc', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_constraint('parent_student_assoc_student_email_fkey', 'parent_student_assoc', type_='foreignkey')
    op.drop_constraint('parent_student_assoc_parent_email_fkey', 'parent_student_assoc', type_='foreignkey')
    op.create_foreign_key(None, 'parent_student_assoc', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_student_assoc', 'students', ['student_id'], ['id'])
    op.drop_column('parent_student_assoc', 'parent_email')
    op.drop_column('parent_student_assoc', 'student_email')
    op.drop_constraint('parents_email_key', 'parents', type_='unique')
    op.drop_constraint('students_email_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['matric_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_email_key', 'students', ['email'])
    op.create_unique_constraint('parents_email_key', 'parents', ['email'])
    op.add_column('parent_student_assoc', sa.Column('student_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('parent_student_assoc', sa.Column('parent_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parent_student_assoc', type_='foreignkey')
    op.drop_constraint(None, 'parent_student_assoc', type_='foreignkey')
    op.create_foreign_key('parent_student_assoc_parent_email_fkey', 'parent_student_assoc', 'parents', ['parent_email'], ['email'])
    op.create_foreign_key('parent_student_assoc_student_email_fkey', 'parent_student_assoc', 'students', ['student_email'], ['email'])
    op.drop_column('parent_student_assoc', 'student_id')
    op.drop_column('parent_student_assoc', 'parent_id')
    op.create_unique_constraint('managers_user_id_key', 'managers', ['user_id'])
    # ### end Alembic commands ###
