"""db models typo fix

Revision ID: 201691060a12
Revises: cd144e78ede8
Create Date: 2022-05-27 13:50:53.152926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201691060a12'
down_revision = 'cd144e78ede8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
