"""delete all models

Revision ID: 28196a29ae17
Revises: 6265faf2f22a
Create Date: 2022-05-31 10:53:53.630585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28196a29ae17'
down_revision = '6265faf2f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
