"""fix pk

Revision ID: 28aacd3ac63d
Revises: 8e18eb3ccfdd
Create Date: 2022-06-15 10:46:37.667068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28aacd3ac63d'
down_revision = '8e18eb3ccfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
