"""remove owner fk

Revision ID: 28d378a0e2c6
Revises: 41c06c7a6e4b
Create Date: 2022-05-19 08:50:26.976337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d378a0e2c6'
down_revision = '41c06c7a6e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'schools', ['phone'])
    op.drop_constraint('schools_owner_id_fkey', 'schools', type_='foreignkey')
    op.drop_column('schools', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('schools_owner_id_fkey', 'schools', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'schools', type_='unique')
    # ### end Alembic commands ###
