"""db models rel fix

Revision ID: 33d7b2530e4f
Revises: 6d4da52fc4bc
Create Date: 2022-05-27 13:45:02.397785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7b2530e4f'
down_revision = '6d4da52fc4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edu_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('edu_calendar', sa.String(), nullable=False),
    sa.Column('edu_stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edu_stage'], ['edu_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('edu_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edu_phase'], ['edu_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('edu_phases')
    op.drop_table('edu_stages')
    # ### end Alembic commands ###
