"""add exam  model

Revision ID: 38096b85a89a
Revises: c4177015add0
Create Date: 2022-06-29 11:41:59.429546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38096b85a89a'
down_revision = 'c4177015add0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('[^"\\\\]*(?:\\\\.[^"\\\\]*)*"', sa.NullType(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    # ### end Alembic commands ###
