"""1-to-1 rel admin-school

Revision ID: 3e8ece6e7d48
Revises: e8e6c9b8bb38
Create Date: 2022-05-27 12:58:55.695198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8ece6e7d48'
down_revision = 'e8e6c9b8bb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
