"""add owner id and relationship

Revision ID: 41c06c7a6e4b
Revises: c93b31e4c7d5
Create Date: 2022-05-18 15:57:07.917705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c06c7a6e4b'
down_revision = 'c93b31e4c7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('schools', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schools', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schools', 'edu_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('schools', 'term_alloction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'schools', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'admin_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'admin_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.alter_column('schools', 'term_alloction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schools', 'edu_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schools', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('schools', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('schools', 'owner_id')
    # ### end Alembic commands ###
