"""add new models

Revision ID: 55e0a55e6707
Revises: be3e7d5e18fd
Create Date: 2022-06-30 14:17:57.290541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55e0a55e6707'
down_revision = 'be3e7d5e18fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('student_matric', sa.Integer(), nullable=False),
    sa.Column('amount_payed', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_day_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['academic_day_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('exam_attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_matric', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('exam_grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_matric', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), server_default='0', nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('exam_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('candidates', sa.Integer(), server_default='0', nullable=True),
    sa.Column('highest_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('lowest_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('average_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('success_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('failure_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('observations', sa.String(), server_default='Nothing to report', nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.add_column('class_attendance', sa.Column('period_id', sa.Integer(), nullable=False))
    op.drop_constraint('class_attendance_subject_id_key', 'class_attendance', type_='unique')
    op.create_unique_constraint(None, 'class_attendance', ['period_id'])
    op.drop_constraint('class_attendance_subject_id_fkey', 'class_attendance', type_='foreignkey')
    op.create_foreign_key(None, 'class_attendance', 'periods', ['period_id'], ['id'], ondelete='CASCADE')
    op.drop_column('class_attendance', 'subject_id')
    op.add_column('exams', sa.Column('name', sa.String(), nullable=False))
    op.add_column('exams', sa.Column('duration', sa.Float(), nullable=False))
    op.add_column('exams', sa.Column('start_time', sa.String(), nullable=False))
    op.add_column('exams', sa.Column('end_time', sa.String(), nullable=False))
    op.add_column('exams', sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('exams', 'participants')
    op.drop_column('exams', 'average_score')
    op.drop_column('exams', 'lowest_score')
    op.drop_column('exams', 'highest_score')
    op.drop_column('exams', 'failure_rate')
    op.drop_column('exams', 'observations')
    op.drop_column('exams', 'success_rate')
    op.add_column('fees', sa.Column('name', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fees', 'name')
    op.add_column('exams', sa.Column('success_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('observations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('failure_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('highest_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('lowest_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('average_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exams', 'date')
    op.drop_column('exams', 'end_time')
    op.drop_column('exams', 'start_time')
    op.drop_column('exams', 'duration')
    op.drop_column('exams', 'name')
    op.add_column('class_attendance', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_attendance', type_='foreignkey')
    op.create_foreign_key('class_attendance_subject_id_fkey', 'class_attendance', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_attendance', type_='unique')
    op.create_unique_constraint('class_attendance_subject_id_key', 'class_attendance', ['subject_id'])
    op.drop_column('class_attendance', 'period_id')
    op.drop_table('exam_stats')
    op.drop_table('exam_grades')
    op.drop_table('exam_attendances')
    op.drop_table('periods')
    op.drop_table('payments')
    op.drop_table('academic_days')
    op.drop_table('timetables')
    # ### end Alembic commands ###
