"""fix ops models

Revision ID: 5ef825ce824f
Revises: 50417a530740
Create Date: 2022-06-29 10:21:48.226469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef825ce824f'
down_revision = '50417a530740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('edu_phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edu_phase_id'], ['edu_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_year_name', sa.String(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_name'], ['academic_years.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('syllabus', sa.String(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('teacher_mail', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_name'], ['academic_years.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_mail'], ['staff.email'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('[^"\\\\]*(?:\\\\.[^"\\\\]*)*"', sa.NullType(), server_default='0', nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('class_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('student_matric', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('[^"\\\\]*(?:\\\\.[^"\\\\]*)*"', sa.NullType(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.add_column('grades', sa.Column('supervisor_mail', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'staff', ['supervisor_mail'], ['email'], ondelete='CASCADE')
    op.add_column('students', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'grades', ['grade_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'grade_id')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'supervisor_mail')
    op.drop_table('exams')
    op.drop_table('class_attendance')
    op.drop_table('assessments')
    op.drop_table('subjects')
    op.drop_table('fees')
    op.drop_table('terms')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
