"""add boolean to manager model

Revision ID: 619ec25a7545
Revises: 010fb44edf5a
Create Date: 2022-06-01 09:01:28.698855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619ec25a7545'
down_revision = '010fb44edf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('is_manager', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'is_manager')
    # ### end Alembic commands ###
