"""set 'autoincrement=True' for all 'id'

Revision ID: 631e3505886f
Revises: 5d113c2a19a6
Create Date: 2022-06-16 10:13:56.277323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631e3505886f'
down_revision = '5d113c2a19a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
