"""many-many rel. fix

Revision ID: 6965c17e1b12
Revises: 9be317842bd6
Create Date: 2022-06-07 14:50:39.551130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6965c17e1b12'
down_revision = '9be317842bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
