"""db models trim

Revision ID: 6d4da52fc4bc
Revises: 8215aed87aec
Create Date: 2022-05-27 13:28:48.785735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4da52fc4bc'
down_revision = '8215aed87aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edu_phases')
    op.drop_table('edu_stages')
    op.drop_table('grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('edu_phase', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edu_phase'], ['edu_phases.id'], name='grades_edu_phase_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grades_pkey')
    )
    op.create_table('edu_stages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('edu_stages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='edu_stages_school_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='edu_stages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('edu_phases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edu_calendar', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edu_stage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edu_stage'], ['edu_stages.id'], name='edu_phases_edu_stage_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='edu_phases_pkey')
    )
    # ### end Alembic commands ###
