"""fix  models

Revision ID: 6fa2dcb4e669
Revises: afa38d8869b7
Create Date: 2022-07-07 12:29:54.460554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa2dcb4e669'
down_revision = 'afa38d8869b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'term_genres', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'term_genres', type_='unique')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'school_id')
    # ### end Alembic commands ###
