"""assoc typo fix

Revision ID: 7aedb99c2a17
Revises: 6965c17e1b12
Create Date: 2022-06-08 16:56:22.291348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aedb99c2a17'
down_revision = '6965c17e1b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parent_student_association_parent_email_fkey', 'parent_student_association', type_='foreignkey')
    op.drop_constraint('parent_student_association_student_email_fkey', 'parent_student_association', type_='foreignkey')
    op.create_foreign_key(None, 'parent_student_association', 'parents', ['parent_email'], ['email'])
    op.create_foreign_key(None, 'parent_student_association', 'students', ['student_email'], ['email'])
    op.add_column('parents', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('parents_user_email_key', 'parents', type_='unique')
    op.create_unique_constraint(None, 'parents', ['email'])
    op.drop_constraint('parents_user_email_fkey', 'parents', type_='foreignkey')
    op.create_foreign_key(None, 'parents', 'users', ['email'], ['email'], ondelete='CASCADE')
    op.drop_column('parents', 'user_email')
    op.add_column('staff', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('staff_user_email_key', 'staff', type_='unique')
    op.create_unique_constraint(None, 'staff', ['email'])
    op.drop_constraint('staff_user_email_fkey', 'staff', type_='foreignkey')
    op.create_foreign_key(None, 'staff', 'users', ['email'], ['email'], ondelete='CASCADE')
    op.drop_column('staff', 'user_email')
    op.add_column('students', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('students_user_email_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['email'])
    op.drop_constraint('students_user_email_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['email'], ['email'], ondelete='CASCADE')
    op.drop_column('students', 'user_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_email_fkey', 'students', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_user_email_key', 'students', ['user_email'])
    op.drop_column('students', 'email')
    op.add_column('staff', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_foreign_key('staff_user_email_fkey', 'staff', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint(None, 'staff', type_='unique')
    op.create_unique_constraint('staff_user_email_key', 'staff', ['user_email'])
    op.drop_column('staff', 'email')
    op.add_column('parents', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key('parents_user_email_fkey', 'parents', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint(None, 'parents', type_='unique')
    op.create_unique_constraint('parents_user_email_key', 'parents', ['user_email'])
    op.drop_column('parents', 'email')
    op.drop_constraint(None, 'parent_student_association', type_='foreignkey')
    op.drop_constraint(None, 'parent_student_association', type_='foreignkey')
    op.create_foreign_key('parent_student_association_student_email_fkey', 'parent_student_association', 'students', ['student_email'], ['user_email'])
    op.create_foreign_key('parent_student_association_parent_email_fkey', 'parent_student_association', 'parents', ['parent_email'], ['user_email'])
    # ### end Alembic commands ###
