"""refactor models

Revision ID: 7cee3c16ac25
Revises: 8942202d5f9e
Create Date: 2022-07-04 17:37:15.945975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cee3c16ac25'
down_revision = '8942202d5f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_grades', sa.Column('student_matric', sa.Integer(), nullable=False))
    op.drop_constraint('exam_grades_student_id_key', 'exam_grades', type_='unique')
    op.create_unique_constraint(None, 'exam_grades', ['student_matric'])
    op.drop_constraint('exam_grades_student_id_fkey', 'exam_grades', type_='foreignkey')
    op.create_foreign_key(None, 'exam_grades', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_column('exam_grades', 'student_id')
    op.drop_constraint('fees_academic_year_id_fkey', 'fees', type_='foreignkey')
    op.drop_constraint('fees_term_id_fkey', 'fees', type_='foreignkey')
    op.drop_column('fees', 'term_id')
    op.drop_column('fees', 'academic_year_id')
    op.add_column('payments', sa.Column('student_matric', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'payments', ['student_matric'])
    op.create_foreign_key(None, 'payments', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'student_matric')
    op.add_column('fees', sa.Column('academic_year_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fees', sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fees_term_id_fkey', 'fees', 'terms', ['term_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fees_academic_year_id_fkey', 'fees', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('exam_grades', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_grades', type_='foreignkey')
    op.create_foreign_key('exam_grades_student_id_fkey', 'exam_grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_grades', type_='unique')
    op.create_unique_constraint('exam_grades_student_id_key', 'exam_grades', ['student_id'])
    op.drop_column('exam_grades', 'student_matric')
    # ### end Alembic commands ###
