"""create users and schools tables

Revision ID: 806de9d2fd33
Revises: 
Create Date: 2022-05-20 09:45:22.762499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806de9d2fd33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_student', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_parent', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_owner', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('admin_level', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rccm_code', sa.Integer(), nullable=True),
    sa.Column('nif_code', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_acc_name', sa.String(), nullable=True),
    sa.Column('bank_acc_num', sa.BigInteger(), nullable=True),
    sa.Column('edu_level', sa.String(), nullable=False),
    sa.Column('term_alloction', sa.String(), nullable=False),
    sa.Column('is_accredited', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    op.drop_table('users')
    # ### end Alembic commands ###
