"""1-to-1 rel fix admin-school

Revision ID: 8215aed87aec
Revises: 3e8ece6e7d48
Create Date: 2022-05-27 13:25:31.043884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8215aed87aec'
down_revision = '3e8ece6e7d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
