"""refactor  models

Revision ID: 83188c4d8da9
Revises: 6fa2dcb4e669
Create Date: 2022-07-08 09:07:25.345138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83188c4d8da9'
down_revision = '6fa2dcb4e669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
