"""user(admin)-school 1-to-1 rel. mod

Revision ID: 86ababeeec6c
Revises: 9af124bdde62
Create Date: 2022-05-30 16:29:54.921653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ababeeec6c'
down_revision = '9af124bdde62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.drop_constraint('schools_admin_id_fkey', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_admin_id_fkey', 'schools', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.alter_column('schools', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    # ### end Alembic commands ###
