"""add prnt stud many-many rel.

Revision ID: 9be317842bd6
Revises: d288ad5a6c9a
Create Date: 2022-06-07 10:45:50.333304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be317842bd6'
down_revision = 'd288ad5a6c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
