"""user(admin)-school multi fk mod

Revision ID: a851fcc214bc
Revises: 86ababeeec6c
Create Date: 2022-05-30 16:49:58.618745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a851fcc214bc'
down_revision = '86ababeeec6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schools_admin_id_fkey', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'users', ['admin_id'], ['admin_id'])
    op.add_column('users', sa.Column('admin_id', sa.Integer(), server_default='0', nullable=True))
    op.create_unique_constraint(None, 'users', ['admin_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'admin_id')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_admin_id_fkey', 'schools', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
