"""assoc fix

Revision ID: a97ebc86801a
Revises: 4dfd3aad0489
Create Date: 2022-06-08 17:47:10.653207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97ebc86801a'
down_revision = '4dfd3aad0489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_student_assoc',
    sa.Column('parent_email', sa.String(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_email'], ['parents.email'], ),
    sa.ForeignKeyConstraint(['student_email'], ['students.email'], ),
    sa.PrimaryKeyConstraint('parent_email', 'student_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_student_assoc')
    # ### end Alembic commands ###
