"""refactor  models

Revision ID: ad5d997002a9
Revises: a116d309e7b7
Create Date: 2022-07-08 10:12:57.643917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d997002a9'
down_revision = 'a116d309e7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'class_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classes', 'supervisor_mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'supervisor_mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('classes', 'class_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
