"""fix  models

Revision ID: afa38d8869b7
Revises: 5fa7753c80e0
Create Date: 2022-07-07 11:48:32.266370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa38d8869b7'
down_revision = '5fa7753c80e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edu_phases', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('edu_stages', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edu_stages', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('edu_phases', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
