"""fix user model

Revision ID: b5744767ffcb
Revises: 631e3505886f
Create Date: 2022-06-28 09:56:17.702153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5744767ffcb'
down_revision = '631e3505886f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
