"""update exam  model

Revision ID: be3e7d5e18fd
Revises: f2b3c845ab4c
Create Date: 2022-06-29 12:08:24.081484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3e7d5e18fd'
down_revision = 'f2b3c845ab4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('exams', sa.Column('success_rate', sa.Float(), nullable=True))
    op.add_column('exams', sa.Column('failure_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'failure_rate')
    op.drop_column('exams', 'success_rate')
    op.drop_column('exams', 'genre')
    # ### end Alembic commands ###
