"""fix  models

Revision ID: c5e109434bf6
Revises: d4a0c580e759
Create Date: 2022-07-06 16:09:42.846770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e109434bf6'
down_revision = 'd4a0c580e759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assoc_exam_stats_student_matric_fkey', 'assoc_exam_stats', type_='foreignkey')
    op.create_foreign_key(None, 'assoc_exam_stats', 'students', ['student_matric'], ['matric'])
    op.drop_constraint('assoc_payment_student_matric_fkey', 'assoc_payment', type_='foreignkey')
    op.create_foreign_key(None, 'assoc_payment', 'students', ['student_matric'], ['matric'])
    op.drop_constraint('class_attendances_student_matric_fkey', 'class_attendances', type_='foreignkey')
    op.create_foreign_key(None, 'class_attendances', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('exam_attendances_student_matric_fkey', 'exam_attendances', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attendances', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('exam_grades_student_matric_fkey', 'exam_grades', type_='foreignkey')
    op.create_foreign_key(None, 'exam_grades', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('payments_student_matric_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.add_column('staff', sa.Column('matric', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'staff', ['matric'])
    op.add_column('students', sa.Column('matric', sa.Integer(), nullable=False))
    op.drop_constraint('students_matric_id_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['matric'])
    op.drop_column('students', 'matric_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('matric_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_matric_id_key', 'students', ['matric_id'])
    op.drop_column('students', 'matric')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'matric')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_student_matric_fkey', 'payments', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_grades', type_='foreignkey')
    op.create_foreign_key('exam_grades_student_matric_fkey', 'exam_grades', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_attendances', type_='foreignkey')
    op.create_foreign_key('exam_attendances_student_matric_fkey', 'exam_attendances', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_attendances', type_='foreignkey')
    op.create_foreign_key('class_attendances_student_matric_fkey', 'class_attendances', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'assoc_payment', type_='foreignkey')
    op.create_foreign_key('assoc_payment_student_matric_fkey', 'assoc_payment', 'students', ['student_matric'], ['matric_id'])
    op.drop_constraint(None, 'assoc_exam_stats', type_='foreignkey')
    op.create_foreign_key('assoc_exam_stats_student_matric_fkey', 'assoc_exam_stats', 'students', ['student_matric'], ['matric_id'])
    # ### end Alembic commands ###
