"""user-manager-school  rel. update

Revision ID: c850733fed06
Revises: 168ba730033f
Create Date: 2022-05-31 10:30:33.502171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c850733fed06'
down_revision = '168ba730033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schools_manager_id_fkey', 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'managers', ['manager_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.create_foreign_key('schools_manager_id_fkey', 'schools', 'managers', ['manager_id'], ['id'])
    # ### end Alembic commands ###
