"""connect users to schools in 1-to-1 relationship

Revision ID: ccb62ee9f0ff
Revises: 806de9d2fd33
Create Date: 2022-05-20 11:30:15.683569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb62ee9f0ff'
down_revision = '806de9d2fd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
