"""fix parent_student_assoc model

Revision ID: cecb13c8f634
Revises: da8ac3d64000
Create Date: 2022-06-15 09:49:25.127461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb13c8f634'
down_revision = 'da8ac3d64000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_parent', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matric_id', sa.Integer(), nullable=False),
    sa.Column('is_student', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'email'),
    sa.UniqueConstraint('matric_id')
    )
    op.create_table('parent_student_assoc',
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('student_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_email'], ['parents.email'], ),
    sa.ForeignKeyConstraint(['student_email'], ['students.email'], ),
    sa.UniqueConstraint('parent_email'),
    sa.UniqueConstraint('student_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_student_assoc')
    op.drop_table('students')
    op.drop_table('parents')
    # ### end Alembic commands ###
