"""add prnt stud staff models

Revision ID: d288ad5a6c9a
Revises: 619ec25a7545
Create Date: 2022-06-07 10:41:49.697981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd288ad5a6c9a'
down_revision = '619ec25a7545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sec_level', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_parent', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_email'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matric_id', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'matric_id', 'user_email'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matric_id', sa.Integer(), nullable=False),
    sa.Column('is_student', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'matric_id', 'user_email'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('parent_student_association',
    sa.Column('parent_email', sa.String(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_email'], ['parents.user_email'], ),
    sa.ForeignKeyConstraint(['student_email'], ['students.user_email'], ),
    sa.PrimaryKeyConstraint('parent_email', 'student_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_student_association')
    op.drop_table('students')
    op.drop_table('staff')
    op.drop_table('parents')
    op.drop_table('subroles')
    # ### end Alembic commands ###
