"""abstract admins table from users table

Revision ID: d5a4a971f027
Revises: ccb62ee9f0ff
Create Date: 2022-05-20 13:13:47.502917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a4a971f027'
down_revision = 'ccb62ee9f0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_owner', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('admin_level', sa.Integer(), server_default=sa.text('128'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE')
    )
    op.drop_column('users', 'is_super_admin')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'is_parent')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'admin_level')
    op.drop_column('users', 'is_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_owner', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('admin_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_parent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_student', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('admins')
    # ### end Alembic commands ###
