"""add assocs

Revision ID: da96a64b3a85
Revises: 7a759b17f520
Create Date: 2022-07-04 10:08:41.440848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da96a64b3a85'
down_revision = '7a759b17f520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), server_default='0', nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'exam_id'),
    sa.UniqueConstraint('exam_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('exam_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidates', sa.Integer(), server_default='0', nullable=True),
    sa.Column('highest_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('lowest_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('average_score', sa.Float(), server_default='0', nullable=True),
    sa.Column('success_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('failure_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('observations', sa.String(), server_default='Nothing to report', nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'exam_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('association_exam_attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('student_matric', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['exam_attendances.id'], ),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ),
    sa.UniqueConstraint('attendance_id'),
    sa.UniqueConstraint('student_matric')
    )
    op.create_table('association_exam_grades',
    sa.Column('exam_grade_id', sa.Integer(), nullable=True),
    sa.Column('student_matric', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_grade_id'], ['exam_grades.id'], ),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], ),
    sa.UniqueConstraint('exam_grade_id'),
    sa.UniqueConstraint('student_matric')
    )
    op.create_unique_constraint(None, 'payments', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_table('association_exam_grades')
    op.drop_table('association_exam_attendance')
    op.drop_table('exam_stats')
    op.drop_table('exam_grades')
    op.drop_table('exam_attendances')
    # ### end Alembic commands ###
