"""fix  models

Revision ID: dc4367110fea
Revises: c5e109434bf6
Create Date: 2022-07-06 16:12:40.641667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4367110fea'
down_revision = 'c5e109434bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_payment')
    op.drop_table('assoc_exam_stats')
    op.drop_constraint('class_attendances_student_matric_fkey', 'class_attendances', type_='foreignkey')
    op.create_foreign_key(None, 'class_attendances', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('exam_attendances_student_matric_fkey', 'exam_attendances', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attendances', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('exam_grades_student_matric_fkey', 'exam_grades', type_='foreignkey')
    op.create_foreign_key(None, 'exam_grades', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.drop_constraint('payments_student_matric_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'students', ['student_matric'], ['matric'], ondelete='CASCADE')
    op.add_column('staff', sa.Column('matric', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'staff', ['matric'])
    op.add_column('students', sa.Column('matric', sa.Integer(), nullable=False))
    op.drop_constraint('students_matric_id_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['matric'])
    op.drop_column('students', 'matric_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('matric_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_matric_id_key', 'students', ['matric_id'])
    op.drop_column('students', 'matric')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'matric')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_student_matric_fkey', 'payments', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_grades', type_='foreignkey')
    op.create_foreign_key('exam_grades_student_matric_fkey', 'exam_grades', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_attendances', type_='foreignkey')
    op.create_foreign_key('exam_attendances_student_matric_fkey', 'exam_attendances', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_attendances', type_='foreignkey')
    op.create_foreign_key('class_attendances_student_matric_fkey', 'class_attendances', 'students', ['student_matric'], ['matric_id'], ondelete='CASCADE')
    op.create_table('assoc_exam_stats',
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_matric', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='assoc_exam_stats_exam_id_fkey'),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], name='assoc_exam_stats_student_matric_fkey'),
    sa.UniqueConstraint('exam_id', name='assoc_exam_stats_exam_id_key'),
    sa.UniqueConstraint('student_matric', name='assoc_exam_stats_student_matric_key')
    )
    op.create_table('assoc_payment',
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_matric', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='assoc_payment_payment_id_fkey'),
    sa.ForeignKeyConstraint(['student_matric'], ['students.matric_id'], name='assoc_payment_student_matric_fkey'),
    sa.UniqueConstraint('payment_id', name='assoc_payment_payment_id_key'),
    sa.UniqueConstraint('student_matric', name='assoc_payment_student_matric_key')
    )
    # ### end Alembic commands ###
