"""new db update

Revision ID: e8e6c9b8bb38
Revises: d5a4a971f027
Create Date: 2022-05-27 11:47:21.008356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e6c9b8bb38'
down_revision = 'd5a4a971f027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edu_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('edu_calendar', sa.String(), nullable=False),
    sa.Column('edu_stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edu_stage'], ['edu_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('edu_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edu_phase'], ['edu_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admins')
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_column('schools', 'is_accredited')
    op.drop_column('schools', 'edu_level')
    op.drop_column('schools', 'term_alloction')
    op.add_column('users', sa.Column('firstname', sa.String(), server_default='Teslim', nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(), server_default='Balogun', nullable=False))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_parent', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('admin_level', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'admin_level')
    op.drop_column('users', 'is_super_admin')
    op.drop_column('users', 'is_owner')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_parent')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.add_column('schools', sa.Column('term_alloction', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('edu_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('is_accredited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('schools', 'is_active')
    op.create_table('admins',
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_owner', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin_level', sa.INTEGER(), server_default=sa.text('128'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admins_admin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', name='admins_pkey')
    )
    op.drop_table('grades')
    op.drop_table('edu_phases')
    op.drop_table('edu_stages')
    # ### end Alembic commands ###
