"""update exam  model

Revision ID: f2b3c845ab4c
Revises: bf0160a03171
Create Date: 2022-06-29 11:50:49.566013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2b3c845ab4c'
down_revision = 'bf0160a03171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('highest_score', sa.Float(), nullable=True))
    op.add_column('exams', sa.Column('lowest_score', sa.Float(), nullable=True))
    op.add_column('exams', sa.Column('average_score', sa.Float(), nullable=True))
    op.add_column('exams', sa.Column('participants', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('observations', sa.String(), nullable=True))
    op.drop_column('exams', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('exams', 'observations')
    op.drop_column('exams', 'participants')
    op.drop_column('exams', 'average_score')
    op.drop_column('exams', 'lowest_score')
    op.drop_column('exams', 'highest_score')
    # ### end Alembic commands ###
